---
grails:
    profile: web
    codegen:
        defaultPackage: online.contacts.book
    gorm:
        reactor:
            events: false  # Whether to translate GORM events into Reactor events

info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'

spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
                - text/html
                - application/xhtml+xml
            js: text/javascript
            json:
                - application/json
                - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
                - application/hal+json
                - application/hal+xml
            xml:
                - text/xml
                - application/xml

    urlmapping:
        cache:
            maxsize: 1000

    controllers:
        defaultScope: singleton

    converters:
        encoding: UTF-8

    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none

    app:
        upload:
            path: "C:/Users/vgmen/OneDrive/Documentos/Faculdade/projetosPessoais/Intersistemas/first-steps/grails-tutorial-contacts-book-master/grails-tutorial-contacts-book-master/src/main/groovy/webapp/contact-image"

endpoints:
    jmx:
        unique-names: true

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false
        cache.region.factory_class: 'org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory'
        singleSession: true  # configure OSIV singleSession mode
        flush.mode: 'manual'  # OSIV session flush mode outside of transactional context

environments:
    development:
        dataSource:
            pooled: true
            jmxExport: true
            driverClassName: org.mariadb.jdbc.Driver
            username: root
            password: 'vgrm2404'
            dbCreate: update
            url: jdbc:mariadb://localhost:3307/contacts
            dialect: org.hibernate.dialect.MariaDB103Dialect
    test:
        dataSource:
            pooled: true
            jmxExport: true
            driverClassName: org.mariadb.jdbc.Driver
            username: root
            password: 'vgrm2404'
            dbCreate: update
            url: jdbc:mariadb://localhost:3307/contacts
            dialect: org.hibernate.dialect.MariaDB103Dialect
    production:
        dataSource:
            pooled: true
            jmxExport: true
            driverClassName: org.mariadb.jdbc.Driver
            username: root
            password: 'vgrm2404'
            dbCreate: update
            url: jdbc:mariadb://localhost:3307/contacts
            dialect: org.hibernate.dialect.MariaDB103Dialect
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2  # TRANSACTION_READ_COMMITTED

app:
    upload:
        path: "C:/Users/vgmen/OneDrive/Documentos/Faculdade/projetosPessoais/Intersistemas/first-steps/grails-tutorial-contacts-book-master/grails-tutorial-contacts-book-master/src/main/groovy/webapp/"
